platform :ios, '8.0'

use_frameworks!

pod 'AFNetworking', '~> 2.2'
pod 'SDWebImage', '~> 3.6'
pod 'SVProgressHUD', :head
pod 'BlocksKit'
pod 'JSONModel', '~> 0.13'
pod 'MMDrawerController', '~> 0.5.7'
pod 'MJExtension'
pod 'MJRefresh'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'AVOSCloud'
pod 'SWTableViewCell', '~> 0.3.7'
pod 'FDFullscreenPopGesture', :git => 'git://github.com/forkingdog/FDFullscreenPopGesture', :commit => 'da1efbf53f5fdd17090d5b30e4cd497a23827b58'
pod 'MQMaskController', :podspec => '../vb/vb/Utils/Podspec/MQMaskController.podspec'
pod 'MQPullToRefresh', :podspec => '../vb/vb/Utils/Podspec/MQPullToRefresh.podspec'