platform :ios, '8.0'

use_frameworks!

pod 'AFNetworking', '~>2.2'
pod 'SVProgressHUD', '~>1.0'
pod 'SVPullToRefresh', '~>0.4'
pod 'JSONModel', '~>0.13'
pod 'MJExtension'
pod 'BlocksKit'
pod 'SDWebImage', '~>3.6'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'MMDrawerController', '~> 0.5.7'
#pod 'Kingfisher', '~> 1.4'